server:
    servlet:
        contextPath: /v1
spring:
    ai:
        azure:
            openai:
                apiKey: ${OPEN_API_KEY}
                endpoint: https://customerserviceopenai.openai.azure.com/
                chat:
                    options:
                        deploymentName: PayProsOAIDeployment